#!/usr/bin/env ruby

inverse=`tput smso` rescue "\e[7m"
normal=`tput rmso`  rescue "\e[0m"

error = %r{
  psql:
  (?<file>[^:]+):
  (?<line>\d+):
  \s+ERROR:.*at\scharacter\s+
  (?<pos>\d+)
}x
args = error.match(ARGV[0])
last_line = args[:line].to_i - 1
pos = args[:pos].to_i

lines = IO.readlines(args[:file])
declaration = lines[0..last_line].reverse.find_index {|l| l =~ /create (or replace)? function/i }
function = lines[(last_line - declaration)..last_line].join

puts function[(pos - 100)..(pos - 1)] + inverse + function[pos] + normal + function[(pos + 1)..(pos + 100)]
